### ISSUE TITLE
Hello,John，very sorry for disturbing you，You still remember the contract of the eos-escrow？

### ISSUE THREAD

**Issue by redshround** [EOSIO/demux-js-eos#19]
I am a developer of eos，See your comments about escorw on eosbet。I want to ask you about the excrow contract. Are you finished? Or have you found a replacement, if you have any, can you share it with me, thank you very much!

**Comment by flux627** [comment]
Hi, I'm not sure what you are asking, and I'm not sure which John you are referring to. (There is no active developer on this repo named John).

I'm closing this and ask that you try contacting this individual in a private communication channel.
