### ISSUE TITLE
how to let client side know the fork activity with this framework

### ISSUE THREAD

**Issue by crazybits** [EOSIO/demux-js-eos#22]
when demux detect the fork block, any way to get the required infor?

**Comment by chris-allnutt** [comment]
In the specific implementation, Postgres, for instance, you can look at the rollback functionality that occurs when a fork has occurred.  Going to mention @flux627 he will know if we store any state data in the event of a fork to reference that it happened.

**Comment by crazybits** [comment]
@chris-allnutt ,thanks ,follow your advice ,seems the rollback can only get the fallback block number, can we get the full block, include the producer infor?

**Comment by flux627** [comment]
What's the use-case?

**Comment by crazybits** [comment]
@flux627  we would like to know which producer cause the fork, this infor could help producer to self-check their bp node.

**Comment by flux627** [comment]
@crazybits Sorry on the delayed reply. I think this functionality might be outside the scope of what Demux is made for- accumulating state based on blockchain events. Forks are not really events. Forks change what the events are (from the perspective of Demux), but are not events themselves.

That said, you could do this via Effects. Create a new ActionReader that emits a `newblock` action at the beginning of every block that contains your required information, and subscribe an effect that saves this information somewhere. If you ever get repeat blocks, you know there was a rollback and can analyze accordingly.

Closing this, but feel free to continue the conversation with any followup questions.
