### ISSUE TITLE
restart stopped when there is fork detected.

### ISSUE THREAD

**Issue by leochan007** [EOSIO/demux-js-eos#28]
0|www      | indexState:{ _id: 5c04dc8cb98dfadfa4dc9c20,
0|www      |   __v: 0,
0|www      |   blockHash: '01674e4e05ce9f0891bc9cbf12809dcc230560339de00caeaf0ad5e2dc6d63bd',
0|www      |   blockNumber: 23547470,
0|www      |   handlerVersionName: 'v1',
0|www      |   isReplay: false,
0|www      |   createTime: 2018-12-03T09:49:02.432Z,
0|www      |   updateTime: 2018-12-03T09:49:02.432Z }
0|www      | blockHash:01674e4e05ce9f0891bc9cbf12809dcc230560339de00caeaf0ad5e2dc6d63bd blockNumber:23547470handlerVersionName:v1
0|www      | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:

/root/.pm2/logs/www-error.log last 15 lines:
0|www      | (node:33) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
0|www      | (node:33) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
0|www      | Error: Cannot seek to block before configured startAtBlock.
0|www      |     at NodeosActionReader.<anonymous> (/root/demux_backend/node_modules/demux-eos/node_modules/demux/dist/AbstractActionReader.js:91:23)
0|www      |     at Generator.next (<anonymous>)
0|www      |     at /root/demux_backend/node_modules/demux-eos/node_modules/demux/dist/AbstractActionReader.js:7:71
0|www      |     at new Promise (<anonymous>)
0|www      |     at __awaiter (/root/demux_backend/node_modules/demux-eos/node_modules/demux/dist/AbstractActionReader.js:3:12)
0|www      |     at NodeosActionReader.seekToBlock (/root/demux_backend/node_modules/demux-eos/node_modules/demux/dist/AbstractActionReader.js:86:16)
0|www      |     at BaseActionWatcher.<anonymous> (/root/demux_backend/node_modules/demux/dist/BaseActionWatcher.js:62:45)
0|www      |     at Generator.next (<anonymous>)
0|www      |     at fulfilled (/root/demux_backend/node_modules/demux/dist/BaseActionWatcher.js:4:58)
0|www      |     at <anonymous>
0|www      |     at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by flux627** [comment]
Please try version 3, as this may have been fixed. If there is still a problem, feel free to re-open this , and try to post more of your code to help diagnose the problem.
