### ISSUE TITLE
How to declare Global Variable in Demux?

### ISSUE THREAD

**Issue by johnworthley** [EOSIO/demux-js-eos#78]
Hi! I am having trouble declaring a global variable in Demux which doesn't reset after effecting every EOS Transfer. Is there a way to declare this within the Updaters folder?

**Comment by jeffreyssmith2nd** [comment]
The Updaters/Effects have a `context` parameter on their apply/run functions that can be used to pass information through to each of them.

https://github.com/EOSIO/demux-js/blob/develop/src/interfaces.ts#L62

If that isn't what you're looking for, if you can explain your use case a bit more that may help figure out what you need.

**Comment by johnworthley** [comment]
Considering storing the global variable on eosio on a memo transaction to be later retrieved when necessary

**Comment by flux627** [comment]
The point of the Action Handler is to persist state accumulatively, which should be accessible between each action / block. If you need to temporarily persist data between each action *in the same block*, you can mutate the context object and it will persist between actions / effects.
