### ISSUE TITLE
StateHistoryPostgresActionReader Issues with 1.8.1 Postgres database.

### ISSUE THREAD

**Issue by elnoxvie** [EOSIO/demux-js-eos#98]
I seem to hit issue with 1.8.1 PostGres. Any ideas how to fix this? 

![image](https://user-images.githubusercontent.com/200763/62292598-56c11080-b499-11e9-805b-cd7b55b1c5be.png)

**Comment by chris-allnutt** [comment]
@elnoxvie looks like history tools didn't create it's tables in the database.  I would recommend verifying the tables exist before starting demux.

**Comment by jeffreyssmith2nd** [comment]
To be compatible with the latest history-tools, you'll need to use the develop branch releases of the demux packages. These can be found under the `@latest` tag on npm.

**Comment by elnoxvie** [comment]
@jeffreyssmith2nd  thanks. It's working now.
